### PR TITLE
remove-AzureRMResourceGroup as Job

### PR DESCRIPTION
**Pull request by renaudwangler**
Hello.
I was tired of waiting for the sequential deletion of resource Groups after lab completion.
I propose this version which start all resource group removal in a row and then wait for all completion.
I tested it in the VM provided with the lab and got no problem for the entire labs.

### CODE REVIEW

**Comment by polichtm** [comment]
I might be missing something - but what's the reason you are waiting for the completion of the deprovisioning script? You can simply launch the provisioning script for the next lab from a new Window PowerShell session.
rgds
Marcin

**Comment by renaudwangler** [comment]
So, I'm probably the one how missed something :)
In the first version of the labs, I'm conviced (but maybe wrongly) the reset-azure script removed everything from the Azure Pass account.
So I told students not to use multiple instances of setup-azure and/or reset-azure.
I may have missed the change in behaviour announcement (and I don't find this obvious).
The other reason the cleaning script may be as short as possible is for the end of the day cleaning : when students are told/want to shutdown the host computer before leaving the classroom.

(Sorry if I'm not completely clear and/or if my text was not as kind as I wanted it to be, English is not my natural language).

Renaud.

**Comment by polichtm** [comment]
Hi Renaud,
You are correct regarding setup-azure and reset-azure, however, the current provisioning/deprovisioning scripts (which, btw. are named differently) have been in place for quite a while (at least since rev. C). The deprovisioning script removes only resource groups provisioned in the current module. The last demo in each module, which includes instructions to run Remove-20533xEnvironment) contains the following statement:
"This script removes resource groups provisioned in the demonstrations of this module. To avoid any unintended data loss, we recommend that you use a separate Azure subscription provisioned specifically for this course."
In addition, I'm no sure I'm following your rationale regarding the benefit of using jobs at the end of the day. If students shut down their computers, then the jobs would NOT run to completion. As a matter of fact, using jobs in this scenario might give students false impression that the jobs completed - and leave Azure resources in place (resulting in unintended charges). Hope this makes sense - pls let me know if any clarification is needed
rgds
Marcin

**Comment by renaudwangler** [comment]
Hi Marcin :)

Your statement is very clear, mine is not : I wrote a small change in the deprovisioning script to launch RG removals as jobs before waiting for all the jobs to complete : the script won't end before all the jobs have...
The only change I suggest here is to be able to delete RG in parallel, if there is any problem with this proposition I won't be upset : I was only willing to help enhance our teaching environment ;)

**Comment by polichtm** [comment]
Hi Renaud
your suggestions and comments are always welcomed and valued.
To accomplish truly parallel execution, we'd need to look into implementing PowerShell workflows - which is actually a fairly significant undertaking. Considering that, at this point, there is no support for workflows in PowerShell Core (which we'll likely moving to at some point), we will investigate other ways to address your suggestion.
rgds
Marcin

**Comment by renaudwangler** [comment]
Marcin,
Last message on this topic from my side :)
I did not suggest an enhancement : I did a Pull Request on a small change I made to the script.
I agree with the workflow overhead : that's why I used simple powershell jobs.
Anyway: thank you for taking time to answer us.

Greetings from France!

**Comment by polichtm** [comment]
Hi Renaud,
valid point... ;)
I hope that you don't mind if I won't merge it - as I mentioned earlier, I'd rather avoid any potential confusion among students regarding completion of the script
rgds
Marcin

**Pull request closed without merging**
