### PR TITLE
Changed the script to relative path

### PR DESCRIPTION
**Pull request by tibor19**
In order to be able to run the labs from your own machine, and from any folder, I updated the PowerShell modules to use relative paths.

### CODE REVIEW

**Comment by polichtm** [comment]
Tiberiu,
have you actually tested all the modules with the updates you are suggesting?
rgds
Marcin

**Comment by tibor19** [comment]
Yes. The only thing that is not changed (and it doesn't need changing) is the SourceManifest.xml file for module 5.

**Comment by itbland** [comment]
I agree that relative paths should be preferred over "_hard-coding_" a path, (and I ran a couple of quick tests in the Lab On Demand copies of this lab with no ill effects--Looks Good! 👍 .) However, we would need instructions to be added that if the **AllFiles** are extracted anywhere other than the **E: drive**, that the **PSModulePath** needs to be updated on that computer to point to the new location. [Modifying the PSModulePath Installation Path](https://msdn.microsoft.com/en-us/library/dd878326(v=vs.85).aspx)

**Comment by tibor19** [comment]
Agreed about the PSModulePath, however my change do not affect the current lab setup as it includes the path already.

**Comment by itbland** [comment]
Yes, to clarify: No changes are needed to the current lab instructions, an additional note should be added to the **Readme in the Build folder** explaining that if no E: drive was present on the computer that was being used, an alternate location could be chosen. (And maybe a small script to update the PSModulePath and extract the Allfiles?)

**Comment by polichtm** [comment]
Pls note that the intention is to support the lab environment on the lab VM only

**Pull request merged**
