### PR TITLE
Lab AK 01 and 02 corrections

### PR DESCRIPTION
**Pull request by itbland**
Lab AK 01
Lines 33-38, corrected list format
Line 65, added bold to URL
Lines 69, 71, 107, 159, removed extra space
Line 91, 151, 153 move period outside of bold
Line 138, 155, added bold format to italics part of storage account name
Line 146 & 149 (new numbering) added line for note formatting
Line 141, added "select the radio button for Use existing"
Line 217, added escape characters to backspaces in path
Line 221, changed the method to create a unique name to conform with previous method "DDMMYYab"
Line 245, added escape character to "#"
Line 249, added lines to ensure that the two lines of code stay as two lines in docx
Line 256, added "After the command completes"

Lab AK 02
Line 14, page is already open, nothing to do but look!
Lines 26, corrrected bold formatting, removed "location" (not a variable) arranged list of variables to match file
Lines 139-161, added missing command and renumbered (UAC prompt)
Lines 160 & 166 (new numbering), added lines to set off note & results box
Lines 171, 204, 405, bolded URL
Lines 175, , (spell-check correction) left hand --> left-hand
Lines 181 & 214, added escape characters to path
Line 187, added path to file name.
Line 195, added dot backslash note
Line 208, "Browse" replaced by "More settings" in Azure Portal
Lines 222-263, corrected numbering error
Line 283, keyboard press will activate student's machine not the VM, replaced with Start button
Lines 309 & 327, removed incorrect space after "**" in bold formatting
Line 339, should be all lower-case
Line 369, included complete interface name in bold formatting, added bold formatting to IP address
Lines 387-395, corrected numbering error
Line 406, (new) added sign-out and close RDP session
Lines 423-447, corrected numbering error
Line 518, added line to properly format the "Result" line

### CODE REVIEW

**Comment by itbland** [comment]
I don’t get it—This is why I refuse to teach this course.
I can understand if you do not want formatting changes, but why are you removing the error corrections? I can’t afford a week every time I teach this class to proof-read the updated class files because you refuse to accept even simple error correction. Pandoc deletes most of a path in every file. There are often spaces after the bold formatting characters that have the word render as “** Azure**” instead of “Azure” in bold. The errors may not appear in the HTML rendering, but using Pandoc, per the instructions, results in an unusable file that I am embarrassed to give to my students. I am obviously wasting my time sending corrections and will not do so any longer.

-Eric Bland, MCT

**Comment by polichtm** [comment]
Hi Eric,
given the amount of edits you recommended (which, btw. I merged into the current version of the file), would you mind clarifying what specifically you have an issue with? 
Wouldn't removing bold formatting characters altogether (which I did, since they didn't seem relevant in this case) resolve the issue you originally brought up?
thnx
Marcin

**Comment by itbland** [comment]
Here is the pandoc docx render of the path you “corrected” in LAB_AK_01 by removing the bold formatting:

1.           In the Windows PowerShell ISE window, open the D:0101Starter.ps1 file.
Here is an example of one of the many copy/paste errors (I presume) where the bold formatting has an extra space after the initial **:

6.        At the PowerShell prompt, create a new resource group for the web app by using the locname variables.
There are so many changes because there is so much wrong with the files. I noted every change, giving the reason for each one in the comments, so that if you wanted to reject where I just added bold formatting you could, leaving the mistake corrections.

Also, a large number of changes occur because of the numbering being wrong after almost every bulleted list in every file. That results in 20+ lines, each time, just being renumbered.

-Eric

**Comment by polichtm** [comment]
Eric,
The pandoc rendering issue should be fixed now.
Hopefully you’ll find the next version of the course more palatable…

Thnx
Marcin

**Pull request merged**
