### PR TITLE
Get specific access key changed

### PR DESCRIPTION
**Pull request by molenaar**
https://msdn.microsoft.com/en-us/library/mt607145.aspx

Example 2: Get a specific access key for a Storage account
 
This command gets a specific key for a Storage account. This command works for Azure PowerShell version 1.4, and later versions.

Windows PowerShell
PS C:\> (Get-AzureRmStorageAccountKey -ResourceGroupName "RG01" -AccountName "MyStorageAccount").Value[0]
 
This command gets a specific key for a Storage account. This command works for Azure PowerShell version 1.3.2, and previous versions.

Windows PowerShell
PS C:\> (Get-AzureRmStorageAccountKey -ResourceGroupName "RG01" -AccountName "MyStorageAccount").Key1

### CODE REVIEW

**Comment by polichtm** [comment]
As far as I can tell, the existing approach works fine - can you clarify why you are suggesting changing it?
rgds
Marcin

**Comment by polichtm** [comment]
Leave a comment

**Comment by polichtm** [comment]
We'll need to look into this a bit closer - there might be some environments running an older version of the Azure PowerShell modules

**Comment by molenaar** [comment]
I can imagine that. It should also be better to rewrite all script modules to ARM and remove all the ASM stuff. However, that's a lot of work...

**Comment by polichtm** [comment]
updated the script to take into account both options

**Pull request closed without merging**
